config/routes.rb
Rails.application.routes.draw do

  resources :merkle_users
  
  get 'requisitions/clone'
  get 'datadictionarylist/index'

  resources :data_dictionaries
  
  resources :requisitions

  resources :jobapps

  resources :users do
    member do
      get :applying   # /users/1/applying   applying_user_path(1)
    end
  end

  resources :relationships

  resources :sessions, only: [:new, :create, :destroy]

  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/newjob',  to: 'jobapps#new',          via: 'get'

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/dict_og', to: 'static_pages#table_managed_hr_data_dict_OG', via: 'get'

  match 'clone', to: 'requisitions#clone', via: 'get'

end

app/models/merkle_user.rb
class MerkleUser < ActiveRecord::Base
end

app/controllers/merkle_users_controller.rb
class MerkleUsersController < ApplicationController
  before_action :set_merkle_user, only: [:show, :edit, :update, :destroy]

  # GET /merkle_users
  # GET /merkle_users.json
  def index
    @merkle_users = MerkleUser.all
    @datatext1 = params[:text1]
  end

  # GET /merkle_users/1
  # GET /merkle_users/1.json
  def show
  end

  # GET /merkle_users/new
  def new
    @merkle_user = MerkleUser.new
  end

  # GET /merkle_users/1/edit
  def edit
  end

  # POST /merkle_users
  # POST /merkle_users.json
  def create
    @merkle_user = MerkleUser.new(merkle_user_params)

    respond_to do |format|
      if @merkle_user.save
        format.html { redirect_to @merkle_user, notice: 'Merkle user was successfully created.' }
        format.json { render :show, status: :created, location: @merkle_user }
      else
        format.html { render :new }
        format.json { render json: @merkle_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /merkle_users/1
  # PATCH/PUT /merkle_users/1.json
  def update
    respond_to do |format|
      if @merkle_user.update(merkle_user_params)
        format.html { redirect_to @merkle_user, notice: 'Merkle user was successfully updated.' }
        format.json { render :show, status: :ok, location: @merkle_user }
      else
        format.html { render :edit }
        format.json { render json: @merkle_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /merkle_users/1
  # DELETE /merkle_users/1.json
  def destroy
    @merkle_user.destroy
    respond_to do |format|
      format.html { redirect_to merkle_users_url, notice: 'Merkle user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_merkle_user
      @merkle_user = MerkleUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def merkle_user_params
      params.require(:merkle_user).permit(:user_name, :user_psd, :eng_name, :chn_name, :email, :bu, :location, :mgr, :position_title, :user_role)
    end
end

app/helpers/merkle_users_helper.rb
module MerkleUsersHelper
end

app/views/merkle_users/_form.html.erb
<%= form_for(@merkle_user) do |f| %>
  <% if @merkle_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@merkle_user.errors.count, "error") %> prohibited this merkle_user from being saved:</h2>

      <ul>
      <% @merkle_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :user_psd %><br>
    <%= f.text_field :user_psd %>
  </div>
  <div class="field">
    <%= f.label :eng_name %><br>
    <%= f.text_field :eng_name %>
  </div>
  <div class="field">
    <%= f.label :chn_name %><br>
    <%= f.text_field :chn_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :bu %><br>
    <%= f.text_field :bu %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :mgr %><br>
    <%= f.text_field :mgr %>
  </div>
  <div class="field">
    <%= f.label :position_title %><br>
    <%= f.text_field :position_title %>
  </div>
  <div class="field">
    <%= f.label :user_role %><br>
    <%= f.text_field :user_role %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/merkle_users/edit.html.erb
<h1>Editing merkle_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @merkle_user %> |
<%= link_to 'Back', merkle_users_path %>

app/views/merkle_users/index.html.erb
<h1>Listing merkle_users</h1>


<table class="table table-striped table-hover table-bordered" id="sample_editable_1">
  <thead>
    <tr>
      <th>User name</th>
      <th>User psd</th>
      <th>Eng name</th>
      <th>Chn name</th>
      <th>Email</th>
      <th>Bu</th>
      <th>Location</th>
      <th>Mgr</th>
      <th>Position title</th>
      <th>User role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @merkle_users.each do |merkle_user| %>
      <tr>
        <td><%= merkle_user.user_name %></td>
        <td><%= merkle_user.user_psd %></td>
        <td><%= merkle_user.eng_name %></td>
        <td><%= merkle_user.chn_name %></td>
        <td><%= merkle_user.email %></td>
        <td><%= merkle_user.bu %></td>
        <td><%= merkle_user.location %></td>
        <td><%= merkle_user.mgr %></td>
        <td><%= merkle_user.position_title %></td>
        <td><%= merkle_user.user_role %></td>
        
        <!-- <script type="text/javascript">
        	window.onload = function(){
        		alert("test1");
        		var test1 = document.getElementsByTagName("input").value;
        		alert(test1);
        	}
        </script> -->
        <!-- <td><%= link_to 'Show', merkle_user %></td> -->
        <!-- <td><%= link_to 'Edit', edit_merkle_user_path(merkle_user) %></td> -->
        <td><a class="edit" href="<%= merkle_user.update_columns( :user_role => 333) %>" remote="true">Edit</a></td>
        <td> <%= link_to 'Destroy', merkle_user, method: :delete, data: { confirm: 'Are you sure?' } %> </td>
      </tr>
    <% end %>
  </tbody>
</table>




<br>

<%= link_to 'New Merkle user', new_merkle_user_path %>

app/views/merkle_users/new.html.erb
<h1>New merkle_user</h1>

<%= render 'form' %>

<%= link_to 'Back', merkle_users_path %>

app/views/merkle_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @merkle_user.user_name %>
</p>

<p>
  <strong>User psd:</strong>
  <%= @merkle_user.user_psd %>
</p>

<p>
  <strong>Eng name:</strong>
  <%= @merkle_user.eng_name %>
</p>

<p>
  <strong>Chn name:</strong>
  <%= @merkle_user.chn_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @merkle_user.email %>
</p>

<p>
  <strong>Bu:</strong>
  <%= @merkle_user.bu %>
</p>

<p>
  <strong>Location:</strong>
  <%= @merkle_user.location %>
</p>

<p>
  <strong>Mgr:</strong>
  <%= @merkle_user.mgr %>
</p>

<p>
  <strong>Position title:</strong>
  <%= @merkle_user.position_title %>
</p>

<p>
  <strong>User role:</strong>
  <%= @merkle_user.user_role %>
</p>

<%= link_to 'Edit', edit_merkle_user_path(@merkle_user) %> |
<%= link_to 'Back', merkle_users_path %>