config/routes.rb
Rails.application.routes.draw do

  resources :merkle_users
  
  get 'requisitions/clone'
  get 'datadictionarylist/index'

  resources :data_dictionaries
  
  resources :requisitions

  resources :jobapps

  resources :users do
    member do
      get :applying   # /users/1/applying   applying_user_path(1)
    end
  end

  resources :relationships

  resources :sessions, only: [:new, :create, :destroy]

  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/newjob',  to: 'jobapps#new',          via: 'get'

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/dict_og', to: 'static_pages#table_managed_hr_data_dict_OG', via: 'get'

  match 'clone', to: 'requisitions#clone', via: 'get'

end

app/models/jobapp.rb
class Jobapp < ActiveRecord::Base
  has_many :reverse_relationships, foreign_key: "jobapp_id", class_name: "Relationship", dependent: :destroy
  has_many :users, through: :reverse_relationships, source: :user
end

app/controllers/jobapps_controller.rb
class JobappsController < ApplicationController
  load_and_authorize_resource except: [:create]
 
  # GET /jobapps
  # GET /jobapps.json
  def index
    @jobapps = Jobapp.all
  end

  # GET /jobapps/1
  # GET /jobapps/1.json
  def show
    @jobapp = Jobapp.find(params[:id])
  end

  # GET /jobapps/new
  def new
    @jobapp = Jobapp.new
  end

  # GET /jobapps/1/edit
  def edit
    @jobapp = Jobapp.find(params[:id])
  end

  # POST /jobapps
  # POST /jobapps.json
  def create
    @jobapp = Jobapp.new(jobapp_params)

      if @jobapp.save
        flash[:success] = "A new job is created."
        redirect_to @jobapp
      else
        render :new
      end
  end

  # PATCH/PUT /jobapps/1
  # PATCH/PUT /jobapps/1.json
  def update
      if @jobapp.update(jobapp_params)
        flash[:success] = "Jobapp was successfully updated."
        redirect_to @jobapp
      else
        render :edit
      end
  end

  # DELETE /jobapps/1
  # DELETE /jobapps/1.json
  def destroy
    @jobapp.destroy
    respond_to do |format|
      format.html { redirect_to jobapps_url, notice: 'Jobapp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jobapp
      @jobapp = Jobapp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jobapp_params
      params.require(:jobapp).permit(:title, :dept, :num, :description, :requirement)
    end
end

app/helpers/jobapps_helper.rb
module JobappsHelper
end

app/views/jobapps/_apply.html.erb
<%= form_for(current_user.relationships.build(jobapp_id: @jobapp.id)) do |f| %>
<div>
	<%= f.hidden_field :jobapp_id %>
</div>
<%= f.submit "apply", class: "btn btn-lg blue" %>
<% end %>

app/views/jobapps/_form.html.erb
<%= bootstrap_form_for(@jobapp) do |f| %>
	<%= f.alert_message "Please fix the errors below." %>
	<%= f.error_summary %>
	
	<div class="field">
		<%= f.text_field :title %>
	</div>
	<div class="field">
		<%= f.text_field :dept %>
	</div>
	<div class="field">
		<%= f.number_field :num %>
	</div>
	<div class="field">
		<%= f.text_area :description %>
	</div>
	<div class="field">
		<%= f.text_area :requirement %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/jobapps/_stats.html.erb
<a>
	<strong>
		<%= @jobapp.users.count %>
	</strong>
	Appliers
</a>

app/views/jobapps/edit.html.erb
<h1>Editing jobapp</h1>

<%= render 'form' %>

<%= link_to 'Show', @jobapp %> |
<%= link_to 'Back', jobapps_path %>

app/views/jobapps/index.html.erb
<div class="portlet box yellow">
	<div class="portlet-title">
		<div class="caption">
			<i class="ico-table"></i>All Job List
		</div>
		<div class="tools">
			<a href="javascript:;" class="collapse"></a>
			<a href="javascript:;" class="reload"></a>
			<a href="javascript:;" class="remove"></a>
		</div>
	</div>
	<div class="portlet-body">
		<div class="clearfix">
			<div class="btn-group">
				<% if current_user.recruiter? %>
				<a href="<%= new_jobapp_path%>">
				<button id="sample_editable_1_new" class="btn blue">
					Add Job <i class="icon-plus-sign"></i>
				</button> </a>
				<% end %>
			</div>
		</div>

		<table class="table table-striped table-bordered table-hover" id="sample_2">
			<thead>
				<tr>
					<th>Title</th>
					<th>Dept</th>
					<th>Hire Num</th>
					<th>Create Date</th>
					<% if can? :update, Jobapp %>
						<th>#Apply</th>
					<% end %>
					<th>Action</th>
				</tr>
			</thead>

			<tbody>

				<% @jobapps.each do |jobapp| %>
				<tr class="odd gradeX">
					<td><%= link_to jobapp.title, jobapp %></td>
					<td><%= jobapp.dept %></td>
					<td><%= jobapp.num %></td>
					<td><%= jobapp.created_at %></td>
					<% if can? :update, jobapp %>
					<td>
						
						<%= jobapp.users.count %>
					</td>
					<% end %>
					<td>
							<% if current_user && !current_user.recruiter? && !current_user.applying?(jobapp) %>
							    <%= link_to 'Apply', jobapp %>
							 <% end %>
							<% if current_user && !current_user.recruiter? && current_user.applying?(jobapp) %>
							    <p style="color:red">
							    	Applied!
							    </p>
							<% end %>
							
							<% if can? :update, jobapp %>
								<%= link_to 'Edit', edit_jobapp_path(jobapp), class: "btn blue" %>
							<% end %>
							<% if can? :destroy, jobapp %>
								<%= link_to 'Destroy', jobapp, method: :delete, data: { confirm: 'Are you sure?' },  class: "btn yellow" %>
							<% end %>
					</td>
				</tr>
				<% end %>

			</tbody>

		</table>

	</div>
</div>
<br>

<% if can? :new, Jobapp%>
<ul class="pager">
<li>
<%= link_to 'New Job', new_jobapp_path ,class: "btn blue"%>
</li>
</ul>
<% end %>

app/views/jobapps/new.html.erb
<div class="container-narrow">
	<% provide(:title, 'Create Job') %> <h1>Create a new job:</h1>

	<%= render 'form' %>

	<%= link_to 'Back', jobapps_path %>

</div>

app/views/jobapps/show.html.erb
<% provide(:title, @jobapp.title) %>
<div class="container">
	<div class="blog-main blog-post">
		<h1 class="blog-post-title"> <%= @jobapp.title %> </h2>
		<% if current_user.applying?(@jobapp) %>
		<blockquote>
			<p style="color:red">
				You have applied this job.
				</style>
			</p>
		</blockquote> <% end %>
		<p class="blog-post-meta">
			Posted <%= time_ago_in_words(@jobapp.created_at) %> ago.
		</p>
		<p>
			Department of <%= @jobapp.dept %>
		</p>
		<p>
			Number: <%= @jobapp.num %>
		</p> 
		<% if signed_in? && !current_user.recruiter? && !current_user.applying?(@jobapp) %>
				<%= render 'apply' %>
		<% end %>
		<% if !signed_in? %>
		<p>
			Please <%= link_to "sign in", signin_path, class: "btn-xs btn-info" %> before applying.
		</p>
		<%end%>
		<% if current_user.recruiter? %>
		<%= render 'stats'%>
		<% end %>
		<hr>
		</hr> <h2>Job description</h2>
		<p>
			<%= simple_format(@jobapp.description) %>
		</p>
		<hr>
		</hr><h2>Requirement</h2>
		<p>
			<%= simple_format(@jobapp.requirement)%>
		</p>
		<ul class="pager">
			<% if can? :update, @jobapp%>
			<li>
				<%= link_to 'Edit', edit_jobapp_path(@jobapp), class: "btn blue" %>
			</li>
			<% end %>
			
			<li>
				<%= link_to 'All Jobs', jobapps_path, class: "btn blue" %>
			</li>
		</ul>
	</div>
</div>