config/routes.rb
Rails.application.routes.draw do

  resources :merkle_users
  
  get 'requisitions/clone'
  get 'datadictionarylist/index'

  resources :data_dictionaries
  
  resources :requisitions

  resources :jobapps

  resources :users do
    member do
      get :applying   # /users/1/applying   applying_user_path(1)
    end
  end

  resources :relationships

  resources :sessions, only: [:new, :create, :destroy]

  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/newjob',  to: 'jobapps#new',          via: 'get'

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/dict_og', to: 'static_pages#table_managed_hr_data_dict_OG', via: 'get'

  match 'clone', to: 'requisitions#clone', via: 'get'

end

app/models/requisition.rb
class Requisition < ActiveRecord::Base
end

app/controllers/requisitions_controller.rb
class RequisitionsController < ApplicationController
  before_action :set_requisition, only: [:show, :edit, :update, :destroy]
  
  def index
    @requisitions=Requisition.all
  end
  
  def new
    @requisition_temp1=Requisition.order("Req_ID DESC").first
    
    if @requisition_temp1.nil?
      @requisition=Requisition.new(:Req_ID => 1)
    else
      @new_ID=Integer(@requisition_temp1.Req_ID)+1
      @requisition=Requisition.new(:Req_ID => @new_ID)
    end   
 end
  
  def show
  end
  
  def edit
  end
  
  def clone
    @requisition_temp1 = Requisition.find(params[:id])
    
    @requisition_temp2 = Requisition.order("Req_ID DESC").first
    @requisition_new_ReqID = Integer(@requisition_temp2.Req_ID)+1
    
    @requisition=Requisition.new(:Req_ID =>@requisition_new_ReqID, :Req_NO =>@requisition_temp1.Req_NO, :Position_title =>@requisition_temp1.Position_title, 
                                 :priority =>@requisition_temp1.priority, :job_category =>@requisition_temp1.job_category, :OG => @requisition_temp1.OG,
                                 :Position_Level =>@requisition_temp1.Position_Level, :Location =>@requisition_temp1.Location, :Openings =>@requisition_temp1.Openings,
                                 :Account_information=>@requisition_temp1.Account_information, :hiring_mgr=>@requisition_temp1.hiring_mgr, :job_posting_date => @requisition_temp1.job_posting_date,
                                 :approved_in_RMO_or_Not=>@requisition_temp1.approved_in_RMO_or_Not,:RMO_Open_Date=>@requisition_temp1.RMO_Open_Date,
                                 :preferred_onboard_date=>@requisition_temp1.preferred_onboard_date, :Biz_impact_details=>@requisition_temp1.Biz_impact_details,
                                 :key_words=>@requisition_temp1.key_words, :cahnnel=>@requisition_temp1.cahnnel, :status=>@requisition_temp1.status, :open_to_candidate=>@requisition_temp1.open_to_candidate,
                                 :job_description=>@requisition_temp1.job_description, :desired_skills_and_experience=>@requisition_temp1.desired_skills_and_experience)
  end
  
  
  
  def create
    @requisition = Requisition.new(requisition_params)

    respond_to do |format|
      if @requisition.save
        format.html { redirect_to @requisition, notice: 'Requisition was successfully created.' }
        format.json { render :show, status: :created, location: @requisition }
      else
        format.html { render :new }
        format.json { render json: @requisition.errors, status: :unprocessable_entity }
      end
    end
   end
   
   
   def update
     respond_to do |format|
      if @requisition.update(requisition_params)
        format.html { redirect_to @requisition, notice: 'Requisition was successfully updated.' }
        format.json { render :show, status: :ok, location: @requisition }
      else
        format.html { render :edit }
        format.json { render json: @requisition.errors, status: :unprocessable_entity }
      end
     end
   end
   
   def destroy
    @requisition.destroy
    respond_to do |format|
      format.html { redirect_to requisitions_url, notice: 'Requisition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
   
   
   private
    # Use callbacks to share common setup or constraints between actions.
    def set_requisition
      @requisition = Requisition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def requisition_params
      params.require(:requisition).permit(:Req_ID, :Req_NO, :Position_title, :priority, :job_category, :OG, :Position_Level, :Location, :Openings, :Account_information, :hiring_mgr, :job_posting_date, 
                                          :approved_in_RMO_or_Not, :RMO_Open_Date, :preferred_onboard_date, :Biz_impact_details, :key_words, :cahnnel, :status, :open_to_candidate, :job_description, :desired_skills_and_experience)
    end
   
end

app/helpers/requisitions_helper.rb
module RequisitionsHelper
end

app/views/requisitions/_form.html.erb
<%= form_for(@requisition) do |f| %>
<% if @requisition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@requisition.errors.count, "error") %> prohibited this requisition from being saved:</h2>

      <ul>
      <% @requisition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<!-- BEGIN PAGE CONTAINER-->        

			<div class="container-fluid">



				<!-- BEGIN PAGE CONTENT-->

				<div class="row-fluid">

					<div class="span12">

						<!-- BEGIN EXAMPLE TABLE PORTLET-->

						<div class="portlet box yellow">

							<div class="portlet-title">

								<div class="caption"><i class="ico-edit"></i>New Requisition</div>

							</div>

							<div class="portlet-body form">

								<div class="clearfix">
							

									<div class="btn-group">

										<%= f.submit 'Save', :class => 'btn blue' %>


									</div>
									



								</div>

															<div class="portlet-body form">

												<h3 class="form-section">Requisition Info</h3>

												<div class="row-fluid">

													<div class="span6 ">

														<div class="control-group">

															<label class="control-label">Req_ID</label>

															<div class="controls">

                                                                 <%= f.text_field :Req_ID, :class => "m-wrap span12", :readonly => true %>

															</div>

														</div>

													</div>

													<!--/span-->

													<div class="span6 ">

														<div class="control-group error">

															<label class="control-label">Req_NO</label>

															<div class="controls">

                                                                <%= f.text_field :Req_NO, :class => "m-wrap span12" %>

															</div>

														</div>

													</div>

													<!--/span-->

												</div>

												<!--/row-->

												<div class="row-fluid">

													<div class="span6 ">

														<div class="control-group">

															<label class="control-label">Posotion Title</label>

															<div class="controls">

														<%= f.select :Position_title, options_for_select(%w{ positiontitle1 positiontitle2 posotiontitle3 }, :selected => @requisition.Position_title), {}, {:class=>"m-wrap span12"}  %>


															</div>

														</div>

													</div>

													<!--/span-->

													<div class="span6 ">

														<div class="control-group">

															<label class="control-label" >Priority</label>

															<div class="controls">

																<%= f.select :priority, options_for_select(%w{ High Mid Low }, :selected => @requisition.priority),{}, {:class => "m-wrap span12"} %>


															</div>

														</div>

													</div>

													<!--/span-->

												</div>

												<!--/row-->        

												<div class="row-fluid">

													<div class="span6 ">

														<div class="control-group">

															<label class="control-label">Job Category</label>

															<div class="controls">
                                                               <%= f.select :job_category, options_for_select(%w{ QA DEV BSA }, :selected => @requisition.job_category),{}, {:class => "span12 select2_category"} %> 
															</div>

														</div>

													</div>

													<!--/span-->

													<div class="span6 ">

														<div class="control-group">

															<label class="control-label">OG</label>

															<div class="controls">                                                

															<%= f.select :OG, options_for_select(%w{ TSG QMG ETG }, :selected => @requisition.OG), {},{:class => "span12 select2_category"}  %> 	
															

															</div>

														</div>

													</div>

													<!--/span-->

												</div>


												<!--/row-->                   

												<div class="row-fluid">

													<div class="span12 ">

														<div class="control-group">

															<label class="control-label">Position Level</label>

															<div class="controls">

															<%= f.select :Position_Level, options_for_select(%w{ Junior Senior Lead Manager Director VP}, :selected => @requisition.Position_Level),{}, {:class => "span12 select2_category"} %> 	

															</div>

														</div>

													</div>

												</div>

												<div class="row-fluid">

													<div class="span6 ">

														<div class="control-group">

															<label class="control-label">Location</label>

															<div class="controls">


                                                                <%= f.select :Location, options_for_select(%w{ NanJing ShangHai}, :selected => @requisition.Location ),{}, {:class => "m-wrap span12"}  %> 	
															</div>

														</div>

													</div>

													<!--/span-->

													<div class="span6 ">

														<div class="control-group">

															<label class="control-label" >Openings</label>

															<div class="controls">


                                                                <%= f.text_field :Openings, :class => "m-wrap span12" %>
															</div>

														</div>

													</div>

													<!--/span-->

												</div>

												<!--/row-->           

												<div class="row-fluid">

													<div class="span6 ">

														<div class="control-group">

															<label class="control-label">Account Information</label>

															<div class="controls">

                                                                <%= f.select :Account_information, options_for_select(%w{ Account_information1 Account_information2}, :selected => @requisition.Account_information ),{}, {:class => "m-wrap span12"} %>
															</div>

														</div>

													</div>

													<!--/span-->

													<div class="span6 ">

														<div class="control-group">

															<label class="control-label">Hiring Mgr.</label>

															<div class="controls">
                                                            <%= f.select :hiring_mgr, options_for_select(%w{ hiring_mgr1 hiring_mgr2}, :selected => @requisition.hiring_mgr),{}, {:class => "m-wrap span12"}  %>
															</div>

														</div>

													</div>

													<!--/span-->

												</div>

												<!--/row-->
                                                <div class="row-fluid">

													<div class="span6 ">

														<div class="control-group">

															<label class="control-label">Job Posting Date</label>

															<div class="controls">
                                                                <%= f.date_select :job_posting_date, :selected=>@requisition.job_posting_date %>
															</div>

														</div>

													</div>

													<!--/span-->

													<div class="span6 ">

														<div class="control-group">

															<label class="control-label">Approved in RMO or Not</label>

															<div class="controls">
                                                            <%= f.select :approved_in_RMO_or_Not, options_for_select(%w{ Y N}, :selected => @requisition.approved_in_RMO_or_Not ),{}, {:class => "m-wrap span12"} %>
															</div>

														</div>

													</div>

													<!--/span-->

												</div>

										       <!--/row-->
                                                <div class="row-fluid">

													<div class="span6 ">

														<div class="control-group">

															<label class="control-label">RMO Open Date</label>

															<div class="controls">

                                                                <%= f.date_select :RMO_Open_Date, :selected=>@requisition.RMO_Open_Date %>
															</div>

														</div>

													</div>

													<!--/span-->

													<div class="span6 ">

														<div class="control-group">

															<label class="control-label">Preferred Onboarding Date</label>

															<div class="controls">
                                                            <%= f.date_select :preferred_onboard_date, :selected=>@requisition.preferred_onboard_date %>
															</div>

														</div>

													</div>

													<!--/span-->

												</div>
												
												<!--/row-->
                                                <div class="row-fluid">

													<div class="span6 ">

														<div class="control-group">

															<label class="control-label">Biz Impact Details</label>

															<div class="controls">

                                                                <%= f.text_area :Biz_impact_details, :rows => 2 %>
															</div>

														</div>

													</div>

													<!--/span-->

													<div class="span6 ">

														<div class="control-group">

															<label class="control-label">Keyords</label>

															<div class="controls">
                                                            <%= f.text_field :key_words, :class => "m-wrap span12" %>
                                                            <span class="help-block">input must be seperated by comma</span>
															</div>

														</div>

													</div>

													<!--/span-->

												</div>
												
												<!--/row-->
                                                <div class="row-fluid">

													<div class="span6 ">

														<div class="control-group">

															<label class="control-label">Channel</label>

															<div class="controls">
                                                            <%= f.select :cahnnel, options_for_select(["Job Board","Career Portal","ERBP","Agency","LinkedIn","BBS"], :selected => @requisition.cahnnel),{}, {:class => "m-wrap span12"} %>
                                                                
															</div>

														</div>

													</div>

													<!--/span-->

													<div class="span6 ">

														<div class="control-group">

															<label class="control-label">Status</label>
                                                             <%= f.select :status, options_for_select(["Pending","Closed","Fullfilled","Interviewing","Sourcing"], :selected => @requisition.status ),{}, {:class => "m-wrap span12"} %>
															<div class="controls">
                                                            
															</div>

														</div>

													</div>

													<!--/span-->

												</div>
												
												<div class="row-fluid">

													<div class="span12 ">

														<div class="control-group">

															<label class="control-label">Open to Candidate</label>

															<div class="controls">

															<%= f.select :open_to_candidate, options_for_select(%w{ Yes No}, :selected => @requisition.open_to_candidate ), {}, {:class => "span12 select2_category"} %> 	

															</div>

														</div>

													</div>

												</div>
												     
												     
												<!--/span-->

												</div>
												
												<div class="row-fluid">

													<div class="span12 ">

														<div class="control-group">

															<label class="control-label">Job description</label>

															<div class="controls">

															<%= f.text_area :job_description, :rows => 2 %>

															</div>

														</div>

													</div>

												</div>
												
												
												<!--/span-->

												
												<div class="row-fluid">

													<div class="span12 ">

														<div class="control-group">

															<label class="control-label">Desired Skills And Experience</label>

															<div class="controls">

															<%= f.text_area :desired_skills_and_experience, :rows => 2 %>

															</div>

														</div>

													</div>

												</div>
												        
											</div>
								

										

							</div>

						</div>

						<!-- END EXAMPLE TABLE PORTLET-->

					</div>

				</div>

				

				<!-- END PAGE CONTENT-->


				
<% end %>

app/views/requisitions/clone.html.erb
<h1>clone requisition</h1>

<%= render 'form_for_clone' %>

<%= link_to 'Show', @requisition %> |
<%= link_to 'Back', requisitions_path %>

app/views/requisitions/edit.html.erb
<h1>Editing requisition</h1>

<%= render 'form' %>

<%= link_to 'Show', @requisition %> |
<%= link_to 'Back', requisitions_path %>

app/views/requisitions/index.html.erb
<div class="portlet box yellow">
	<div class="portlet-title">
		<div class="caption">
			<i class="ico-table"></i>Requisition List
		</div>
		<div class="tools">
			<a href="javascript:;" class="collapse"></a>
			<a href="javascript:;" class="reload"></a>
			<a href="javascript:;" class="remove"></a>
		</div>
	</div>

	<div class="portlet-body">

 <table class="table table-striped table-bordered table-hover" id="sample_2">
  <thead>
    <tr>
      <th> Req_ID</th>
      <th> Req_NO</th>
      <th>Position Title</th>
      <th>Priority</th>
      <th> OG</th>
      <th>Location</th>
      <th>Openings</th>
      <th>Hiring Mgr.</th>
      <th>Leading Time</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @requisitions.each do |requisition| %>
       <tr>
       	<td><%= requisition.Req_ID  %></td>
        <td><%= requisition.Req_NO  %></td>
        <td><%= link_to requisition.Position_title, requisition  %></td>
        <td><%= requisition.priority  %></td>
        <td><%= requisition.OG  %></td>
        <td><%= requisition.Location  %></td>
        <td><%= requisition.Openings  %></td>
        <td><%= requisition.hiring_mgr  %></td>
        <td><%= Integer(DateTime.parse(Time.now.to_s)-DateTime.parse(requisition.RMO_Open_Date.to_s)) %></td>
        <td><%= link_to 'Edit', edit_requisition_path(requisition) %>|
        <% if current_user && !current_user.admin? %>
        <%= link_to 'Destroy', requisition, method: :delete, data: { confirm: 'Are you sure?' } %>|
        <% end %>
        <%= link_to 'Clone', clone_path(:id => requisition.id ) %></td>  
       </tr>
       <% end %>
  </tbody>
  
</table>

<br> 

<% if current_user && !current_user.recruiter? %>
<%= link_to 'New Requisition', new_requisition_path, class: "btn blue" %>
<% end %>
</div>
</div>

app/views/requisitions/new.html.erb
<h1>New requisition</h1>

<%= render 'form' %>

 <%= link_to 'Back', requisitions_path %>

app/views/requisitions/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'form_for_show' %>

<%= link_to 'Back', requisitions_path %>

app/views/requisitions/show11.html.erb
<!-- BEGIN PAGE CONTAINER-->        

			<div class="container-fluid">



				<!-- BEGIN PAGE CONTENT-->

				<div class="row-fluid">

					<div class="span12">

						<!-- BEGIN EXAMPLE TABLE PORTLET-->

						<div class="portlet box yellow">

							<div class="portlet-title">

								<div class="caption"><i class="ico-edit"></i>Show Requisition</div>

							</div>

							<div class="portlet-body form">


															<div class="portlet-body form">

												<h3 class="form-section">Requisition Info</h3>

												<div class="row-fluid">

													<div class="span6 ">

														<div class="control-group">

															<label class="control-label">Req_ID</label>

															<div class="controls">

                                                             <%= text_field @requisition.Req_ID %>    

															</div>

														</div>

													</div>

													<!--/span-->

													<div class="span6 ">

														<div class="control-group error">

															<label class="control-label">Req_NO</label>

															<div class="controls">

                                                                <%= text_field @requisition.Req_NO %>

															</div>

														</div>

													</div>

													<!--/span-->

												</div>

												<!--/row-->

												<div class="row-fluid">

													<div class="span6 ">

														<div class="control-group">

															<label class="control-label">Posotion Title</label>

															<div class="controls">

														<%= select( options_for_select( @requisition.position_title ), :class => "m-wrap span12")  %>


															</div>

														</div>

													</div>

													<!--/span-->

													<div class="span6 ">

														<div class="control-group">

															<label class="control-label" >Priority</label>

															<div class="controls">

																<%= select( options_for_select(@requisition.Priority), :class => "m-wrap span12"  ) %>


															</div>

														</div>

													</div>

													<!--/span-->

												</div>

												<!--/row-->        

												<div class="row-fluid">

													<div class="span6 ">

														<div class="control-group">

															<label class="control-label">Job Category</label>

															<div class="controls">
                                                               <%= select( options_for_select(@requisition.job_category), :class => "span12 select2_category"  ) %> 
															</div>

														</div>

													</div>

													<!--/span-->

													<div class="span6 ">

														<div class="control-group">

															<label class="control-label">OG</label>

															<div class="controls">                                                

															<%= select( options_for_select(@requisition.OG), :class => "span12 select2_category"  ) %> 	

															</div>

														</div>

													</div>

													<!--/span-->

												</div>


												<!--/row-->                   

												<div class="row-fluid">

													<div class="span12 ">

														<div class="control-group">

															<label class="control-label">Position Level</label>

															<div class="controls">

															<%= select( options_for_select(@requisition.Position_Level), :class => "span12 select2_category"  ) %> 	

															</div>

														</div>

													</div>

												</div>

												<div class="row-fluid">

													<div class="span6 ">

														<div class="control-group">

															<label class="control-label">Location</label>

															<div class="controls">


                                                                <%= select( options_for_select(@requisition.Location), :class => "m-wrap span12"  ) %> 	
															</div>

														</div>

													</div>

													<!--/span-->

													<div class="span6 ">

														<div class="control-group">

															<label class="control-label" >Openings</label>

															<div class="controls">


                                                                <%= text_field @requisition.Openings, :class => "m-wrap span12" %>
															</div>

														</div>

													</div>

													<!--/span-->

												</div>

												<!--/row-->           

												<div class="row-fluid">

													<div class="span6 ">

														<div class="control-group">

															<label class="control-label">Account Information</label>

															<div class="controls">

                                                                <%= select( options_for_select(@requisition.Account_information), :class => "m-wrap span12"  ) %>
															</div>

														</div>

													</div>

													<!--/span-->

													<div class="span6 ">

														<div class="control-group">

															<label class="control-label">Hiring Mgr.</label>

															<div class="controls">
                                                            <%= select(options_for_select(@requisition.hiring_mgr), :class => "m-wrap span12"  ) %>
															</div>

														</div>

													</div>

													<!--/span-->

												</div>

												<!--/row-->
                                                <div class="row-fluid">

													<div class="span6 ">

														<div class="control-group">

															<label class="control-label">Job Posting Date</label>

															<div class="controls">
                                                                <%= date_select @requisition.job_posting_date, :class => "m-wrap span12" %>
															</div>

														</div>

													</div>

													<!--/span-->

													<div class="span6 ">

														<div class="control-group">

															<label class="control-label">Approved in RMO or Not</label>

															<div class="controls">
                                                            <%= select(options_for_select(@requisition.approved_in_RMO_or_Not), :class => "m-wrap span12"  ) %>
															</div>

														</div>

													</div>

													<!--/span-->

												</div>

										       <!--/row-->
                                                <div class="row-fluid">

													<div class="span6 ">

														<div class="control-group">

															<label class="control-label">RMO Open Date</label>

															<div class="controls">

                                                                <%= date_select @requisition.RMO_Open_Date, :class => "m-wrap span12" %>
															</div>

														</div>

													</div>

													<!--/span-->

													<div class="span6 ">

														<div class="control-group">

															<label class="control-label">Preferred Onboarding Date</label>

															<div class="controls">
                                                            <%= date_select @requisition.preferred_onboard_date, :class => "m-wrap span12" %>
															</div>

														</div>

													</div>

													<!--/span-->

												</div>
												
												<!--/row-->
                                                <div class="row-fluid">

													<div class="span6 ">

														<div class="control-group">

															<label class="control-label">Biz Impact Details</label>

															<div class="controls">

                                                                <%= text_area @requisition.Biz_impact_details, :rows => 2 %>
															</div>

														</div>

													</div>

													<!--/span-->

													<div class="span6 ">

														<div class="control-group">

															<label class="control-label">Keyords</label>

															<div class="controls">
                                                            <%= text_field @requisition.key_words, :class => "m-wrap span12" %>
                                                            <span class="help-block">input must be seperated by comma</span>
															</div>

														</div>

													</div>

													<!--/span-->

												</div>
												
												<!--/row-->
                                                <div class="row-fluid">

													<div class="span6 ">

														<div class="control-group">

															<label class="control-label">Channel</label>

															<div class="controls">
                                                            <%= select( options_for_select(@requisition.cahnnel), :class => "m-wrap span12") %>
                                                                
															</div>

														</div>

													</div>

													<!--/span-->

													<div class="span6 ">

														<div class="control-group">

															<label class="control-label">Status</label>
                                                             <%= select( options_for_select(@requisition.status), :class => "m-wrap span12") %>
															<div class="controls">
                                                            
															</div>

														</div>

													</div>

													<!--/span-->

												</div>
												
												<div class="row-fluid">

													<div class="span12 ">

														<div class="control-group">

															<label class="control-label">Open to Candidate</label>

															<div class="controls">

															<%= select(:open_to_candidate, options_for_select(@requisition.open_to_candidate), :class => "span12 select2_category"  ) %> 	

															</div>

														</div>

													</div>

												</div>
												     
												     
												<!--/span-->

												</div>
												
												<div class="row-fluid">

													<div class="span12 ">

														<div class="control-group">

															<label class="control-label">Job description</label>

															<div class="controls">

															<%= text_area @requisition.job_description, :rows => 2 %>

															</div>

														</div>

													</div>

												</div>
												
												
												<!--/span-->

												
												<div class="row-fluid">

													<div class="span12 ">

														<div class="control-group">

															<label class="control-label">Desired Skills And Experience</label>

															<div class="controls">

															<%= text_area @requisition.desired_skills_and_experience, :rows => 2 %>

															</div>

														</div>

													</div>

												</div>
												        
											</div>
								

										

							</div>

						</div>

						<!-- END EXAMPLE TABLE PORTLET-->

					</div>

				</div>

				
<%= link_to 'Edit', edit_requisition_path(@requisition) %> |
<%= link_to 'Back', requisitions_path %>
				<!-- END PAGE CONTENT-->