config/routes.rb
Rails.application.routes.draw do

  resources :merkle_users
  
  get 'requisitions/clone'
  get 'datadictionarylist/index'

  resources :data_dictionaries
  
  resources :requisitions

  resources :jobapps

  resources :users do
    member do
      get :applying   # /users/1/applying   applying_user_path(1)
    end
  end

  resources :relationships

  resources :sessions, only: [:new, :create, :destroy]

  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/newjob',  to: 'jobapps#new',          via: 'get'

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/dict_og', to: 'static_pages#table_managed_hr_data_dict_OG', via: 'get'

  match 'clone', to: 'requisitions#clone', via: 'get'

end

app/views/layouts/_bsheader.html.erb
<head>

	<meta charset="utf-8" />

	<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Merkle China, Sample App | <%= yield(:title) %></title>

	<%= stylesheet_link_tag    "application", media: "all" %>
	<%= javascript_include_tag "application", media: "all"%>
	<%= csrf_meta_tags %>

	<meta content="width=device-width, initial-scale=1.0" name="viewport" />
	<meta content="" name="description" />
	<meta content="" name="author" />
	<!-- BEGIN GLOBAL MANDATORY STYLES -->
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
	<link href="/assets/media/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
	<link href="/assets/media/css/style-metro.css" rel="stylesheet" type="text/css"/>
	<link href="/assets/media/css/style.css" rel="stylesheet" type="text/css"/>
	<link href="/assets/media/css/style-responsive.css" rel="stylesheet" type="text/css"/>
	<link href="/assets/media/css/default.css" rel="stylesheet" type="text/css" id="style_color"/>
	<link href="/assets/media/css/uniform.default.css" rel="stylesheet" type="text/css"/>
	<link href="/assets/media/css/bootstrap-responsive.min.css" rel="stylesheet" type="text/css"/>
	
	<!-- BEGIN GLOBAL MANDATORY STYLES -->

	<!-- END GLOBAL MANDATORY STYLES -->

	<!-- BEGIN PAGE LEVEL STYLES -->

	
	<!-- END GLOBAL MANDATORY STYLES -->
	<!-- BEGIN PAGE LEVEL STYLES -->
	<link rel="stylesheet" type="text/css" href="/assets/media/css/select2_metro.css" />
	<link rel="stylesheet" href="/assets/media/css/DT_bootstrap.css" />
	<!-- END PAGE LEVEL STYLES -->
	<link rel="shortcut icon" href="media/image/favicon.ico" />
</head>
<!-- END HEAD -->

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small> <a href="http://merkleinc.com/">Merkle inc.</a> HR Team </small>
	<nav>
		<ul>
			<li>
				<%= link_to "About",
				about_path %>
			</li>
			<li>
				<%= link_to "Contact", '#' %>
			</li>
			<li>
				<a href="#">News</a>
			</li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "Home", root_path, id: "logo" %>
			<nav>
				<ul class="nav navbar-nav pull-right">
					<li>
						<%= link_to "Home",    root_path %>
					</li>
					<li>
						<%= link_to "Help",    help_path %>
					</li>
					<li>
						<%= link_to "All Jobs", jobapps_url%>
					</li>
					
					<% if can? :create, Jobapp %>
						<li>
							<%= link_to "Create Job", newjob_path%>
						</li>
						<li>
							<%= link_to "Users", users_path %>
						</li>
					<% end %>
					<% if signed_in? %>
					<li id="fat-menu" class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown"> <%=current_user.name %><b class="caret"></b> </a>
						<ul class="dropdown-menu">
							<li>
								<%= link_to "Profile", current_user %>
							</li>
							<li>
								<%= link_to "Settings", edit_user_path(current_user)%>
							</li>
							<li class="divider"></li>
							<li>
								<%= link_to "Sign out", signout_path, method: "delete" %>
							</li>
						</ul>
					</li>
					
					<% else %>
					<li>
						<%= link_to "Sign in", signin_path %>
					</li>
					<% end %>

				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<!-- BEGIN CONTAINER -->
<div class="page-container row-fluid">
	<!-- BEGIN SIDEBAR -->
	<div class="page-sidebar navbar-collapse collapse">

		<!-- BEGIN SIDEBAR MENU -->
		<ul class="page-sidebar-menu">
			<li class="start ">
				<a href="#"> <i class="icon-home"></i> <span class="title">Dashboard</span> </a>
			</li>
						<li class="">
				<a href="#"> <i class="icon-tasks"></i> <span class="title">To Do List</span> </a>
			</li>

			<li class="">
				<a href="javascript:;"> <i class="icon-cogs"></i> <span class="title">Requisition</span> <span class="arrow "></span> </a>
				<ul class="sub-menu">
					<li >
						<%= link_to 'New Requisition', new_requisition_path %>
					</li>
					<li >
						<a href="<%= requisitions_path%>"> Requisiton List </a>

					</li>
				</ul>

			</li>

			<li class="">

				<a href="javascript:;"> <i class="icon-group"></i> <span class="title">Candidate</span> <span class="arrow "></span> </a>

				<ul class="sub-menu">

					<li >

						<a href="#"> Candidate List</a>

					</li>

					<li >

						<a href="#"> Review </a>

					</li>

				</ul>

			</li>

			<li class="">

				<a href="javascript:;"> <i class="icon-cog"></i> <span class="title">Settings</span> <span class="arrow "></span> </a>

				<ul class="sub-menu">

					<li >

						<a href="<% merkle_users_path %>"> User Management </a>

					</li>

					<li >

						<a href="<%= datadictionarylist_index_path %>"> Data Dictionary </a>

					</li>
				</ul>

			</li>

	
		</ul>

		<!-- END SIDEBAR MENU -->

	</div>
	<!-- END SIDEBAR -->

app/views/layouts/_usertag.html.erb
<% if signed_in?%>
<li class="dropdown user">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown"> <%= gravatar_for current_user %> <span class="username"><%= current_user.name %></span> <i class="icon-angle-down"></i> </a>

	<ul class="dropdown-menu">

		<li>
			<%= link_to raw("<i class=\"icon-user\"></i> My Profile"), current_user %>
		</li>

		<li>
			<a href="page_calendar.html"><i class="icon-calendar"></i> (x)My Calendar</a>
		</li>

		<li>
			<a href="inbox.html"><i class="icon-envelope"></i> (x) My Inbox(3)</a>
		</li>

		<li>
			<a href="#"><i class="icon-tasks"></i> (x) My Tasks</a>
		</li>

		<li class="divider"></li>

		<li>
			<a href="extra_lock.html"><i class="icon-lock"></i> Lock Screen</a>
		</li>

		<li>
			<%= link_to raw("<i class=\"icon-key\"></i> Sign out"), signout_path, method: :delete %>
		</li>

	</ul>

</li>
<% else %>
<li>
	<%= link_to "Sign in", signin_path %>
</li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>


<%= render 'layouts/bsheader'%>

<!-- BEGIN BODY -->

<body class="page-header-fixed">

	<!-- BEGIN HEADER -->

	<div class="header navbar navbar-fixed-top">
		<!-- BEGIN TOP NAVIGATION BAR -->
		<div class="navbar-inner">

			<div class="container-fluid">

				<!-- BEGIN LOGO -->

				<!--<a class="brand" href="index.html">-->
				<a href="/">
				<img width="390px" height="22px" style=margin-top:15px src="/assets/media/image/merkle-logo-tagline_04.png" alt="logo" />
				</a>
                <!--</a>-->

				<!-- END LOGO -->

				<!-- BEGIN RESPONSIVE MENU TOGGLER -->

				<a href="javascript:;" class="navbar-btn collapsed" data-toggle="collapse" data-target=".navbar-collapse">

				<img width="20px" height="22px" style=margin-top:15px src="/assets/media/image/menu-toggler.png" alt="" />

				</a>          

				<!-- END RESPONSIVE MENU TOGGLER -->            

				<!-- BEGIN TOP NAVIGATION MENU -->              

				<ul class="nav pull-right">
					<!-- BEGIN USER LOGIN DROPDOWN -->
					<%= render 'layouts/usertag'%>
					<!-- END USER LOGIN DROPDOWN -->
				</ul>

				<!-- END TOP NAVIGATION MENU --> 

			</div>

		</div>
		<!-- END TOP NAVIGATION BAR -->
	</div>

	<!-- END HEADER -->

	<%= render 'layouts/sidebar'%>
		<!-- BEGIN PAGE -->
		<div class="page-content">
			<div class="container-fluid">
				<!-- BEGIN PAGE CONTENT-->
				<div class="row-fluid">
					<div class="span24">
						<% flash.each do |key, value| %>
						<div class="alert alert-<%= key %>">
							<%= value %>
						</div>
						<% end %>
						<%= yield %>
					</div>
				</div>
			</div>
		</div>
		<!-- END PAGE -->

	</div>

	<!-- END CONTAINER -->

	<!-- BEGIN FOOTER -->
	<%= debug(params) if Rails.env.development? %>
	<div class="footer">

		<div class="footer-inner">

			2014 &copy; HR System by Merkleinc.

		</div>

		<div class="footer-tools">

			<span class="go-top">

			<i class="icon-angle-up"></i>

			</span>

		</div>

	</div>
	<!-- END FOOTER -->
	<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
	<!-- BEGIN CORE PLUGINS -->
	<script src="/assets/media/js/jquery-1.10.1.min.js" type="text/javascript"></script>
	<script src="/assets/media/js/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
	<!-- IMPORTANT! Load jquery-ui-1.10.1.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
	<script src="/assets/media/js/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script>      
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js" type="text/javascript"></script>

	<!--[if lt IE 9]>

	<script src="/assets/media/js/excanvas.min.js"></script>

	<script src="/assets/media/js/respond.min.js"></script>  

	<![endif]-->   

	<script src="/assets/media/js/jquery.slimscroll.min.js" type="text/javascript"></script>

	<script src="/assets/media/js/jquery.blockui.min.js" type="text/javascript"></script>  

	<script src="/assets/media/js/jquery.cookie.min.js" type="text/javascript"></script>

	<script src="/assets/media/js/jquery.uniform.min.js" type="text/javascript" ></script>

	<!-- END CORE PLUGINS -->

	<!-- BEGIN PAGE LEVEL PLUGINS -->

	<script type="text/javascript" src="/assets/media/js/select2.min.js"></script>

	<script type="text/javascript" src="/assets/media/js/jquery.dataTables.js"></script>

	<script type="text/javascript" src="/assets/media/js/DT_bootstrap.js"></script>

	<!-- END PAGE LEVEL PLUGINS -->

	<!-- BEGIN PAGE LEVEL SCRIPTS -->

	<script src="/assets/media/js/app.js"></script>

	<script src="/assets/media/js/table-managed.js"></script>  
	
	<script src="/assets/media/js/table-editable.js"></script>      

	<script>

		jQuery(document).ready(function() {       

		   App.init();
			
		   TableManaged.init();
		   		//alert("111222");
		   TableEditable.init();
		   	//alert("333444");
		});

	</script>

<script type="text/javascript">
	var _gaq = _gaq || [];
	_gaq.push(['_setAccount', 'UA-37564768-1']);
	_gaq.push(['_setDomainName', 'keenthemes.com']);
	_gaq.push(['_setAllowLinker', true]);
	_gaq.push(['_trackPageview']);
	(function() {
		var ga = document.createElement('script');
		ga.type = 'text/javascript';
		ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';
		var s = document.getElementsByTagName('script')[0];
		s.parentNode.insertBefore(ga, s);
	})();
	</script></body>

<!-- END BODY -->

</html>